[package]
name = "sapiesims"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fraction64 = {path = "../fraction64"}
qol = { version = "0.1.5", git = "https://github.com/DrAlta/rust_quality_of_life.git"}

